version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"

conda:
  environment: docs/environment.yaml

sphinx:
  builder: html
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt