version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"

conda:
  environment: docs/environment.yml

sphinx:
  builder: html
  configuration: doc/conf.py

python:
  install:
    - requirements: doc/requirements.txt