name: plantconvert
channels:
- openalea3
- conda-forge
dependencies:
- openalea.plantgl
- openalea.mtg
- numpy
- pip:
  - vtk
  - pygltflib
  - sphinx==7.0.1
  - sphinx_rtd_theme==1.3.0
  - nbsphinx
  - nbsphinx_link