name: plantconvert
channels:
- openalea3
- conda-forge
dependencies:
- openalea.plantgl
- openalea.mtg
- numpy
- pip
- pip:
  - vtk
  - pygltflib
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  - nbsphinx_link