name: plantconvert
channels:
- openalea3
- conda-forge
dependencies:
- openalea.plantgl
- openalea.mtg
- numpy
- pip
pip:
  - openalea.plantconvert
  - vtk
  - pygltflib
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  - nbsphinx_link